# encoding: utf-8

COUNTRY_CODE = {
  ## europe
  'Deutschland' => 'GER',
  'Österreich'  => 'AUT',
  'Dänemark'    => 'DEN',
  'Slowenien'   => 'SVN',
  'Slowakei'    => 'SVK',
  'Polen'       => 'POL',
  'Albanien'    => 'ALB',
  'Serbien'     => 'SRB',
  'Norwegen'    => 'NOR',
  'Frankreich'  => 'FRA',
  ## asia
  'Japan'       => 'JPN',

 "Italien"=>"ITA",
 "Chile"=>"CHI",
 "Nigeria"=>"NGA",
 "Portugal"=>"POR",
 "Schweden"=>"SWE",
 "Spanien"=>"ESP",
 "Kolumbien"=>"COL",
 "Schweiz"=>"SUI",
 "Bulgarien"=>"BUL",
 "Argentinien"=>"ARG",
 "USA"=>"USA",
 "Kroatien"=>"CRO",
 "Brasilien"=>"BRA",
 "Griechenland"=>"GRE",
 "Türkei"=>"TUR",
 "Südkorea"=>"KOR",
 "Ukraine"=>"UKR",
 "Mexiko"=>"MEX",
 "Marokko"=>"MAR",
 "Niederlande"=>"NED",
 "Belgien"=>"BEL",
 "Guinea"=>"GUI",
 "Armenien"=>"ARM",
 "Gabun"=>"GAB",
 "Finnland"=>"FIN",
 "Aserbaidschan"=>"AZE",
 "Peru"=>"PER",
 "Elfenbeinküste"=>"CIV",
 "Tschechien"=>"CZE",
 "Ghana"=>"GHA",
 "Estland"=>"EST",
 "Paraguay"=>"PAR",
 "Kasachstan"=>"KAZ",
 "Kamerun"=>"CMR",
 "Israel"=>"ISR",
 "Australien"=>"AUS",
 "Bosnien-Herzegowina"=>"BIH",
 "Mosambik"=>"MOZ",
 "Ungarn"=>"HUN",
 "Lettland"=>"LTU",
 "Senegal"=>"SEN",
 "Tunesien"=>"TUN",
 "Costa Rica"=>"CRC",
 "Ecuador"=>"ECU",
 "Rumänien"=>"ROU",
 "DR Kongo"=>"COD",
}

