require 'hoe'
require './lib/sportdb/source/footballdata/version.rb'

Hoe.spec 'sportdb-source-footballdata' do

  self.version = SportDb::Source::Footballdata::VERSION

  self.summary = "sportdb-source-footballdata - download & import 22+ top football leagues from 25 seasons back to 1993/94 from Joseph Buchdahl's Football Data website (football-data.co.uk) up and running since 2001 (and updated twice a week)"
  self.description = summary

  self.urls = ['https://github.com/yorobot/football.csv']

  self.author = 'Gerald Bauer'
  self.email = 'opensport@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
    ['fetcher',          '>= 0.4.5'],
    ['footballdb-clubs', '>= 2020.3.30'],
    ['sportdb-import',   '>= 0.2.4'],
  ]

  self.spec_extras = {
   :required_ruby_version => '>= 2.2.2'
  }

end
